language: cpp

os:
  - linux

compiler:
  - gcc

before_intall:
  - pip install --user cpp-coveralls

script:
  - cmake .
  - cmake --build .

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
