language: cpp
compiler:
  - gcc

before_intall:
  - pip install --user cpp-coveralls

script:
  - ./configure --enable-gcov
  - cmake .
  - cmake --build .

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
